//
//  HomeWorker.swift
//  ReignDesignTestApp
//
//  Created by Julián Arias on 15-09-18.
//  Copyright (c) 2018 Maetschl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates: http://clean-swift.com
//

import UIKit
import Alamofire

class HomeWorker {
    func getDataFromApi() {
        Alamofire.request("https://hn.algolia.com/api/v1/search_by_date?query=ios").responseJSON { (responseData) in
            if responseData.data != nil {
                let hackerNewsSearchResult = try? JSONDecoder().decode(HackerNewsSearchResult.self, from: responseData.data!)
            } else {
                
            }

        }
    }
}
