//
//  HomePresenter.swift
//  ReignDesignTestApp
//
//  Created by Julián Arias on 15-09-18.
//  Copyright (c) 2018 Maetschl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates: http://clean-swift.com
//

import UIKit

protocol HomePresentationLogic {
    func presentNews(response: Home.NewsList.Response)
}

class HomePresenter: HomePresentationLogic {
    weak var viewController: HomeDisplayLogic?

    // MARK: Present news

    func presentNews(response: Home.NewsList.Response) {
        var displayedNews: [Home.NewsList.ViewModel.NewsDisplayedData] = []
        for item in response.news {
            let title = item.title
            let info = item.author + " - " + item.date
            let newDisplayedNews = Home.NewsList.ViewModel.NewsDisplayedData(title: title, info: info)
            displayedNews.append(newDisplayedNews)
        }
        let viewModel = Home.NewsList.ViewModel(news: displayedNews)
        viewController?.displayNews(viewModel: viewModel)
    }
}
