//
//  HomeModels.swift
//  ReignDesignTestApp
//
//  Created by Julián Arias on 15-09-18.
//  Copyright (c) 2018 Maetschl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates: http://clean-swift.com
//

import UIKit

enum Home {
    // MARK: Get news
    enum News {
        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
        }
    }
}
