//
//  DetailInteractorTests.swift
//  ReignDesignTestApp
//
//  Created by Julián Arias on 16-09-18.
//  Copyright (c) 2018 Maetschl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import ReignDesignTestApp
import XCTest

class DetailInteractorTests: XCTestCase {
    // MARK: Subject under test

    var sut: DetailInteractor!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupDetailInteractor()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupDetailInteractor() {
        sut = DetailInteractor()
    }

    // MARK: Test doubles

    class DetailPresentationLogicSpy: DetailPresentationLogic {
        var presentUrlWasCalled = false
        func presentUrl(response: Detail.WebView.Response) {
            presentUrlWasCalled = true
        }
    }

    // MARK: Tests

    func testDoSomething() {
        // Given
        let spy = DetailPresentationLogicSpy()
        sut.presenter = spy
        sut.url = URL(string: Configurations.baseUrl)!

        // When
        sut.getUrl()

        // Then
        XCTAssertTrue(spy.presentUrlWasCalled)
    }
}
