//
//  DetailModels.swift
//  ReignDesignTestApp
//
//  Created by Julián Arias on 15-09-18.
//  Copyright (c) 2018 Maetschl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates from: http://clean-swift.com
//

import UIKit

enum Detail {
    // MARK: Show web view

    enum WebView {
        struct Request {
        }
        struct Response {
            var url: URL
        }
        struct ViewModel {
            var url: URL
        }
    }
}
