//
//  DetailPresenter.swift
//  ReignDesignTestApp
//
//  Created by Julián Arias on 15-09-18.
//  Copyright (c) 2018 Maetschl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates from: http://clean-swift.com
//

import UIKit

protocol DetailPresentationLogic {
    func presentUrl(response: Detail.WebView.Response)
}

class DetailPresenter: DetailPresentationLogic {
    weak var viewController: DetailDisplayLogic?

    // MARK: Do something

    func presentUrl(response: Detail.WebView.Response) {
        let viewModel = Detail.WebView.ViewModel(url: response.url)
        viewController?.displayWeb(viewModel: viewModel)
    }
}
