//
//  DetailInteractor.swift
//  ReignDesignTestApp
//
//  Created by Julián Arias on 15-09-18.
//  Copyright (c) 2018 Maetschl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates from: http://clean-swift.com
//

import UIKit

protocol DetailBusinessLogic {
    func getUrl()
}

protocol DetailDataStore {
    var url: URL! { get set }
}

class DetailInteractor: DetailBusinessLogic, DetailDataStore {
    var presenter: DetailPresentationLogic?

    // MARK: Data store
    var url: URL!

    // MARK: Get url
    func getUrl() {
        let response = Detail.WebView.Response(url: url)
        presenter?.presentUrl(response: response)
    }
}
