//
//  HomeInteractorTests.swift
//  ReignDesignTestApp
//
//  Created by Julián Arias on 15-09-18.
//  Copyright (c) 2018 Maetschl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates from: http://clean-swift.com
//

@testable import ReignDesignTestApp
import XCTest

class HomeInteractorTests: XCTestCase {
    // MARK: Subject under test

    var sut: HomeInteractor!
    var worker: HomeWorkerSpy!
    var presenter: HomePresentationLogicSpy!

    let TEST_STRING = "Test String"

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupHomeInteractor()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupHomeInteractor() {
        sut = HomeInteractor()
        worker = HomeWorkerSpy()
        sut.worker = worker
        presenter = HomePresentationLogicSpy()
        sut.presenter = presenter
    }

    // MARK: Tests get data

    func testGetNewsCallApiWorkerGetData() {
        // Given
        let spy = HomePresentationLogicSpy()
        sut.presenter = spy

        // When
        sut.getNews()

        // Then
        XCTAssertTrue(worker.getDataFromApiWasCalled, "getDataFromApi was called from interactor getNews")
    }

    func testGetNewsCallPresentNewsWenWorkerSuccess() {
        // Given
        let spy = HomePresentationLogicSpy()
        sut.presenter = spy
        worker.getDataFromApiShouldReturnError = false

        // When
        sut.getNews()

        // Then
        XCTAssertTrue(worker.getDataFromApiWasCalled, "getDataFromApi was called from interactor getNews")
        XCTAssertTrue(spy.presentSomethingCalled, "PresentNews was called")
    }

    func testGetNewsCallPresentNewsWenWorkerFail() {
        // Given
        let spy = HomePresentationLogicSpy()
        sut.presenter = spy
        worker.getDataFromApiShouldReturnError = true

        // When
        sut.getNews()

        // Then
        XCTAssertTrue(worker.getDataFromApiWasCalled, "getDataFromApi was called from interactor getNews")
        XCTAssertTrue(spy.presentSomethingCalled, "PresentNews was called")
    }

    // MARK: Test remove data
    func testRemoveData() {
        // Given
        let spy = HomePresentationLogicSpy()
        sut.presenter = spy
        sut.data = [News(title: TEST_STRING, author: TEST_STRING, date: TEST_STRING),
                    News(title: TEST_STRING, author: TEST_STRING, date: TEST_STRING),
                    News(title: TEST_STRING, author: TEST_STRING, date: TEST_STRING)]
        let removeRequest = Home.RemoveNews.Request(row: 0)

        // When
        sut.deleteNews(request: removeRequest)

        // Then
        XCTAssertEqual(2, sut.data.count, "2 News in dataStore")
        XCTAssertTrue(spy.presentSomethingCalled, "Present data was called")
    }

    func testRemoveUniqueData() {
        // Given
        let spy = HomePresentationLogicSpy()
        sut.presenter = spy
        sut.data = [News(title: TEST_STRING, author: TEST_STRING, date: TEST_STRING)]
        let removeRequest = Home.RemoveNews.Request(row: 0)

        // When
        sut.deleteNews(request: removeRequest)

        // Then
        XCTAssertEqual(0, sut.data.count, "Nothing in dataStore")
        XCTAssertTrue(spy.presentSomethingCalled, "Present data was called")
    }
}
