//
//  HomePresenterTests.swift
//  ReignDesignTestApp
//
//  Created by Julián Arias on 15-09-18.
//  Copyright (c) 2018 Maetschl. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import ReignDesignTestApp
import XCTest

class HomePresenterTests: XCTestCase {
    // MARK: Subject under test

    var sut: HomePresenter!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupHomePresenter()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupHomePresenter() {
        sut = HomePresenter()
    }

    // MARK: Tests

    func testPresentNewsCallDisplayNews() {
        // Given
        let spy = HomeDisplayLogicSpy()
        sut.viewController = spy
        let response = Home.NewsList.Response(news: [])

        // When
        sut.presentNews(response: response)

        // Then
        XCTAssertTrue(spy.displayNewsWasCalled, "presentSomething(response:) should ask the view controller to display the result")
    }

    func testPresentNewsWithOneNewCallDisplayNews() {
        // Given
        let spy = HomeDisplayLogicSpy()
        sut.viewController = spy
        let news = News(title: "TestTitle", author: "TestAutohr", date: "TestDate")
        let response = Home.NewsList.Response(news: [news])

        // When
        sut.presentNews(response: response)

        // Then
        XCTAssertTrue(spy.displayNewsWasCalled, "presentSomething(response:) should ask the view controller to display the result")
    }
}
